# Cloud Build configuration
steps:
  # Run tests
  # - name: 'python:3.12'
  #   entrypoint: bash
  #   args:
  #     - '-c'
  #     - |
  #       pip install -r ./src/requirements.txt
  #       pip install pytest
  #       python -m pytest tests/ -v || true  # Don't fail the build if tests fail for now
  
  # Build and push multi-platform container images (ARM64 and AMD64)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    secretEnv: ['SERVICE_ACCOUNT_JSON', 'ENV_FILE']
    args:
      - '-c'
      - |
        mkdir -p credentials
        echo "$$SERVICE_ACCOUNT_JSON" > credentials/service-account.json
        echo "$$ENV_FILE" > src/.env      
        docker buildx create --use --name multiarch-builder
        docker buildx build --platform linux/arm64,linux/amd64 \
          -t ${_REGION}-docker.pkg.dev/$PROJECT_ID/document-api/document-api:$SHORT_SHA \
          -t ${_REGION}-docker.pkg.dev/$PROJECT_ID/document-api/document-api:latest \
          --push .
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'document-management-api'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/document-api/document-api:$SHORT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - '${_REGION}'
      - '--service-account'
      - '${_SERVICE_ACCOUNT}'
      - '--allow-unauthenticated'

  # Create Cloud Function source archive
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y zip
        mkdir -p /workspace/function
        cp -r src/functions /workspace/function/
        cd /workspace/function
        zip -r /workspace/function-source.zip .

  # Upload function source to Storage
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gsutil
    args:
      - 'cp'
      - '/workspace/function-source.zip'
      - 'gs://${_PROJECT_ID}-functions/function-source.zip'

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/service-account-json/versions/latest
    env: SERVICE_ACCOUNT_JSON
  - versionName: projects/$PROJECT_ID/secrets/env-file/versions/latest
    env: ENV_FILE

substitutions:
  _REGION: 'eu-west1'  # Matching the GitHub connection region
  _PROJECT_ID: '${PROJECT_ID}'
  _SERVICE_ACCOUNT: 'cloudbuild-sa@hacker2025-team-5-dev.iam.gserviceaccount.com'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/document-api/document-api:$SHORT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/document-api/document-api:latest'
options:
  logging: CLOUD_LOGGING_ONLY